version: '3'
services:
  ui:
    image: "node:12.8"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./ui:/home/node/app
      - ./shared:/home/node/shared
    command: "npm run start:dev"
    env_file:
        - ./shared/.env
        - ./shared/personal.env
    ports:
      - ${PUBLIC_UI_PORT}:8080
    restart: always

  node:
    image: "node:12.8"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./servers/javascript:/home/node/app
      - ./shared:/home/node/shared
    command: "npm run start:dev"
    env_file:
        - ./shared/.env
        - ./shared/personal.env
        - ./shared/private.env
    links:
      - mongo
      - live_server
    ports:
      - ${PUBLIC_SERVER_PORT}:8080

  live_server:
    image: "node:12.8"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./servers/javascript-live:/home/node/app
      - ./shared:/home/node/shared
    command: "npm run start:dev"
    env_file:
        - ./shared/.env
        - ./shared/personal.env
        - ./shared/private.env
    ports:
      - ${PUBLIC_LIVE_PORT}:8080

  mongo:
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    env_file:
        - ./shared/private.env
  # eth:
  #   image: ethereum/client-go
  #   container_name: eth_web
  #   restart: always
  #   ports:
  #     - '8545:8545'
  #     - '30303:30303'
  #   command: "--rpc --rpcaddr '0.0.0.0' --rpcport '9000' "
