const SERVER_HOST = process.env.SERVER_HOST;

const PUBLIC_UI_PORT = process.env.PUBLIC_UI_PORT;
const PUBLIC_SERVER_PROTOCOL = process.env.PUBLIC_SERVER_PROTOCOL;
const PUBLIC_SERVER_HOSTNAME = process.env.PUBLIC_SERVER_HOSTNAME;
const PUBLIC_SERVER_PORT = process.env.PUBLIC_SERVER_PORT;

const PUBLIC_LIVE_PROTOCOL = process.env.PUBLIC_LIVE_PROTOCOL;
const PUBLIC_LIVE_HOSTNAME = process.env.PUBLIC_LIVE_HOSTNAME;
const PUBLIC_LIVE_PORT = process.env.PUBLIC_LIVE_PORT;

const EXTERNAL_SHARED_HOSTNAME = process.env.EXTERNAL_SHARED_HOSTNAME

console.log(process.env)

console.log(
  SERVER_HOST,
  PUBLIC_UI_PORT,
  PUBLIC_SERVER_PORT
)

const TODO_DATABASE_NAME=process.env.TODO_DATABASE_NAME
const TODO_COLLECTION_NAME=process.env.TODO_COLLECTION_NAME


const getDbArgs = {
  url: `${PUBLIC_SERVER_PROTOCOL}:\/\/${EXTERNAL_SHARED_HOSTNAME}:${PUBLIC_SERVER_PORT}`
}

const liveDBArgs = {
  liveUrl: `${PUBLIC_LIVE_PROTOCOL}://${EXTERNAL_SHARED_HOSTNAME}:${PUBLIC_LIVE_PORT}/mongodb/${TODO_DATABASE_NAME}/${TODO_COLLECTION_NAME}`,
}

export {
  getDbArgs,
  liveDBArgs,
  SERVER_HOST,
  PUBLIC_UI_PORT,
  PUBLIC_SERVER_PORT
}
